/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author NandiniCreations
 */
public class Task4_Online_Exam_Questions extends javax.swing.JFrame {

    /**
     * Creates new form Task4_Online_Exam_Questions
     */
    public Task4_Online_Exam_Questions() {
        initComponents();
        questions_panel.setVisible(false);

    }

    void close() {
        JOptionPane.showMessageDialog(this, "Exam Finished");
        new Task4_Online_Exam_Closing().setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Q1 = new javax.swing.ButtonGroup();
        buttonGroup_Q2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        questions_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        start_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        minutes_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seconds_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ONLINE EXAM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        questions_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Q1. Who is the current Prime Minister of India ?");
        questions_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 350, -1));

        buttonGroup_Q1.add(jRadioButton1);
        jRadioButton1.setText("APJ Abdul Kalam");
        questions_panel.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 49, -1, -1));

        buttonGroup_Q1.add(jRadioButton2);
        jRadioButton2.setText("Narender Modi");
        questions_panel.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 49, -1, -1));

        buttonGroup_Q1.add(jRadioButton3);
        jRadioButton3.setText("Ram Nath Kovind");
        questions_panel.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 81, -1, -1));

        buttonGroup_Q1.add(jRadioButton4);
        jRadioButton4.setText("Rahul Gandhi");
        questions_panel.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 81, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Q2. Which is the biggest Continent in the World ?");
        questions_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 128, 350, -1));

        buttonGroup_Q2.add(jRadioButton5);
        jRadioButton5.setText("Asia");
        questions_panel.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 163, -1, -1));

        buttonGroup_Q2.add(jRadioButton6);
        jRadioButton6.setText("Africa");
        questions_panel.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 195, -1, -1));

        buttonGroup_Q2.add(jRadioButton7);
        jRadioButton7.setText("Australia");
        questions_panel.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 163, -1, -1));

        buttonGroup_Q2.add(jRadioButton8);
        jRadioButton8.setText("Russia");
        questions_panel.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 195, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("FINISH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        questions_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 241, -1, -1));

        jPanel1.add(questions_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 500, 280));

        start_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        start_button.setText("START");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(start_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Timer ");

        minutes_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText(":");

        seconds_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel5.setText("2 mins");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(minutes_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconds_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minutes_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(seconds_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        // TODO add your handling code here:
        start_button.setVisible(false);
        questions_panel.setVisible(true);
        Timer timer_sec = new Timer();
        Timer timer_min = new Timer();
        timer_sec.scheduleAtFixedRate(new TimerTask() {
            int i = 0;

            public void run() {
                //seconds_label.setText("" + i);

                if (i == 0) {
                    i = 60;
                }
                --i;
                if (i < 10) {
                    seconds_label.setText("0" + i);
                } else {
                    seconds_label.setText("" + i);
                }
            }
        }, 0, 1000);

        timer_min.scheduleAtFixedRate(new TimerTask() {
            int i = 2;

            public void run() {
                i--;
                if (i < 0) {
                    timer_min.cancel();
                    timer_sec.cancel();
                    minutes_label.setVisible(false);
                    seconds_label.setVisible(false);
                    close();
                }
                minutes_label.setText("0" + i);
            }
        }, 0, 60000);

    }//GEN-LAST:event_start_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Task4_Online_Exam_Closing().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task4_Online_Exam_Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task4_Online_Exam_Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task4_Online_Exam_Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task4_Online_Exam_Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task4_Online_Exam_Questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Q1;
    private javax.swing.ButtonGroup buttonGroup_Q2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JLabel minutes_label;
    private javax.swing.JPanel questions_panel;
    private javax.swing.JLabel seconds_label;
    private javax.swing.JButton start_button;
    // End of variables declaration//GEN-END:variables
}
