/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author NandiniCreations
 */
public class Task4_Online_Exam_Profile extends javax.swing.JFrame {

    /**
     * Creates new form Task4_Online_Exam_Profile
     */
    String userPassed = "";
            

    public Task4_Online_Exam_Profile() {
        initComponents();
        update_panel.setVisible(false);
    }

    public Task4_Online_Exam_Profile(String uname) {
        initComponents();
        userPassed = uname;
        update_panel.setVisible(false);
    }

    static Connection conn = null;
    static Statement stmt = null;
    static ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        update_panel = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        age_label = new javax.swing.JLabel();
        age_tf = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        phone_tf = new javax.swing.JTextField();
        update_submit_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        exam_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ONLINE EXAM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("PROFILE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        name_label.setText("NAME :");

        name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_tfActionPerformed(evt);
            }
        });

        age_label.setText("AGE :");

        phone_label.setText("PHONE :");

        update_submit_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update_submit_button.setText("SUBMIT");
        update_submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_submit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout update_panelLayout = new javax.swing.GroupLayout(update_panel);
        update_panel.setLayout(update_panelLayout);
        update_panelLayout.setHorizontalGroup(
            update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(update_panelLayout.createSequentialGroup()
                        .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_label)
                            .addComponent(age_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(update_panelLayout.createSequentialGroup()
                        .addComponent(phone_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_submit_button)
                            .addComponent(phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        update_panelLayout.setVerticalGroup(
            update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age_label)
                    .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_label)
                    .addComponent(phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(update_submit_button)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(update_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 190));

        update_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update_button.setText("UPDATE PROFILE");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, -1));

        exam_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exam_button.setText("ATTEMPT EXAM");
        exam_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exam_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(exam_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_tfActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        update_panel.setVisible(true);
        
    }//GEN-LAST:event_update_buttonActionPerformed

    private void exam_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exam_buttonActionPerformed
        // TODO add your handling code here:
        new Task4_Online_Exam_Questions().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exam_buttonActionPerformed

    private void update_submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_submit_buttonActionPerformed
        // TODO add your handling code here:
        try {
            String userName = "root";
            String password = "aryan7";
            String url = "jdbc:mysql://localhost:3306/oasis_internship";

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url, userName, password);
            stmt = conn.createStatement();

            String name = name_tf.getText();
            Integer age = Integer.parseInt(age_tf.getText());
            String phone = phone_tf.getText();
            if (age instanceof Integer && phone.length() == 10) {
                stmt.execute("update details set name = \"" + name + "\",age = " + age + ",phone = \"" + phone + "\" where username = \"" + userPassed + "\";");
                JOptionPane.showMessageDialog(this,"Profile Updated");
            }else if(!(age instanceof Integer)){
                JOptionPane.showMessageDialog(this,"Age must be a number");
            }else if(phone.length()!=10){
                JOptionPane.showMessageDialog(this,"Phone no. must be 10 digits");
            }

        } catch (Exception e) {
            System.out.println("Error in update_submit_button : "+e.getMessage());
        }
    }//GEN-LAST:event_update_submit_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task4_Online_Exam_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task4_Online_Exam_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task4_Online_Exam_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task4_Online_Exam_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task4_Online_Exam_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age_label;
    private javax.swing.JTextField age_tf;
    private javax.swing.JButton exam_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel phone_label;
    private javax.swing.JTextField phone_tf;
    private javax.swing.JButton update_button;
    private javax.swing.JPanel update_panel;
    private javax.swing.JButton update_submit_button;
    // End of variables declaration//GEN-END:variables
}
